# .travis.yml
dist: bionic

addons:
  firefox: latest
  chrome: stable

services:
  - xvfb

language: node_js
node_js:
  - 10.15.3
  - "stable"

before_install:
  - stty cols 80

install:
  - npm install

script: 
  - npm run serve