# .travis.yml
language: node_js
node_js:
  - 10.15.3
notifications:
    email:
        recipients:
          - cwtk159x37@gmail.com
        on_success: always
        on_failure: always
install:
  - npm install
script:
  - npm run serve